import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join } from 'node:path';
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const server=createServer(async(q,r)=>{let p=join('dist',decodeURIComponent(q.url.split('?')[0]));
try{ if((await stat(p)).isDirectory()) p=join(p,'index.html'); }catch{ p=p+'.html'; }
try{const b=await readFile(p);r.writeHead(200,{'content-type':MIME[extname(p)]||'application/octet-stream'});r.end(b);}catch{r.writeHead(404);r.end('nf');}});
await new Promise(res=>server.listen(4321,res));
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:2});
await p.goto('http://localhost:4321/projects',{waitUntil:'networkidle'});await p.waitForTimeout(1200);
await p.locator('.case-tile').first().scrollIntoViewIfNeeded();
await p.screenshot({path:'/tmp/tiles.png',clip:{x:0,y:0,width:1440,height:1000}});
await p.goto('http://localhost:4321/',{waitUntil:'networkidle'});await p.waitForTimeout(1800);
const box=await p.locator('[data-carousel="essays"]').boundingBox();
await p.evaluate(y=>window.scrollTo(0,y-120), box.y);
await p.waitForTimeout(700);
await p.screenshot({path:'/tmp/carousel.png',clip:{x:0,y:0,width:1440,height:760}});
await p.goto('http://localhost:4321/',{waitUntil:'networkidle'});await p.waitForTimeout(1500);
const lb=await p.locator('[data-carousel="library"]').boundingBox();
await p.evaluate(y=>window.scrollTo(0,y-140), lb.y);
await p.waitForTimeout(700);
await p.screenshot({path:'/tmp/library.png',clip:{x:0,y:0,width:1440,height:700}});
await b.close();server.close();
