import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join } from 'node:path';
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.avif':'image/avif','.svg':'image/svg+xml'};
const server=createServer(async(q,r)=>{let p=join('dist',decodeURIComponent(q.url.split('?')[0]));
try{ if((await stat(p)).isDirectory()) p=join(p,'index.html'); }catch{ p=p+'.html'; }
try{const b=await readFile(p);r.writeHead(200,{'content-type':MIME[extname(p)]||'application/octet-stream'});r.end(b);}catch{r.writeHead(404);r.end('nf');}});
await new Promise(res=>server.listen(4321,res));
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1440,height:1000}});
await p.goto('http://localhost:4321/about',{waitUntil:'networkidle'});
await p.waitForTimeout(2000);
const read=()=>p.evaluate(()=>document.querySelector('[data-position]').textContent);
console.log('  start:', await read());
await p.click('.arrow.next'); await p.waitForTimeout(900);
console.log('  next click ->', await read());
await p.click('.arrow.next'); await p.waitForTimeout(900);
console.log('  next click ->', await read());
await p.click('.arrow.prev'); await p.waitForTimeout(900);
console.log('  prev click ->', await read());
await p.focus('.arrow.next');
await p.keyboard.press('ArrowRight'); await p.waitForTimeout(900);
console.log('  ArrowRight ->', await read());
await p.keyboard.press('ArrowLeft'); await p.waitForTimeout(900);
console.log('  ArrowLeft  ->', await read());
console.log('  arrows are buttons:', await p.evaluate(()=>[...document.querySelectorAll('.photo-rail .arrow')].every(e=>e.tagName==='BUTTON')));
console.log('  arrow labels:', await p.evaluate(()=>[...document.querySelectorAll('.photo-rail .arrow')].map(e=>e.getAttribute('aria-label')).join(' | ')));
console.log('  all 7 alts:', await p.evaluate(()=>[...document.querySelectorAll('.photo img')].filter(i=>i.alt.length>10).length));
await b.close();server.close();
